In [1]:
#import packages
import pandas as pd
import numpy as np

In [2]:
#load datasets
df1 = pd.read_csv('HDIPercentD.csv')

df2 = pd.read_csv('PopulationData1.csv')

In [3]:
#merge datasets using outer to check for any matching errors
df = pd.merge(df1,df2, on = 'Alpha-3 code', how = 'outer')

In [4]:
#check for matching errors
print(df.to_string())

                       Country Name  Mens Points  Womens Points Alpha-3 code  Percentage Difference  HDI rank  Value                                               Country      YR2021
0                           Albania      1361.81        1346.01          ALB               1.160221      67.0  0.796                                               Albania     2811666
1                           Algeria      1480.59        1288.27          DZA              12.989416      91.0  0.745                                               Algeria    44616626
2                           Andorra      1028.70         751.46          AND              26.950520      40.0  0.858                                               Andorra       77354
3                            Angola      1149.08        1041.91          AGO               9.326592     148.0  0.586                                                Angola    33933611
4               Antigua and Barbuda      1117.01         804.42          ATG              27.984530      71.0  0.788                                   Antigua and Barbuda       98728
5                         Argentina      1770.65        1660.37          ARG               6.228221      47.0  0.842                                             Argentina    45808747
6                           Armenia      1242.42        1072.97          ARM              13.638705      85.0  0.759                                               Armenia     2968128
7                         Australia      1483.73        1906.20          AUS             -28.473509       5.0  0.951                                             Australia    25739256
8                           Austria      1502.47        1813.37          AUT             -20.692593      25.0  0.916                                               Austria     8956279
9                        Azerbaijan      1127.17        1274.50          AZE             -13.070788      91.0  0.745                                            Azerbaijan    10145212
10                          Bahrain      1289.25        1254.12          BHR               2.724840      35.0  0.875                                               Bahrain     1748295
11                       Bangladesh       883.18        1017.16          BGD             -15.170180     129.0  0.661                                            Bangladesh   166303494
12                         Barbados       982.27         966.80          BRB               1.574923      70.0  0.790                                              Barbados      287708
13                          Belarus      1226.55        1457.75          BLR             -18.849619      60.0  0.808                                               Belarus     9340314
14                          Belgium      1821.92        1823.83          BEL              -0.104834      13.0  0.937                                               Belgium    11587882
15                           Belize       950.88         839.85          BLZ              11.676552     123.0  0.683                                                Belize      404915
16                            Benin      1258.71        1020.94          BEN              18.889975     166.0  0.525                                                 Benin    12451031
17                           Bhutan       910.96         769.00          BTN              15.583560     127.0  0.666                                                Bhutan      779900
18                          Bolivia      1298.81        1213.10          BOL               6.599118     118.0  0.692                                               Bolivia    11832936
19           Bosnia and Herzegovina      1403.98        1385.20          BIH               1.337626      74.0  0.780                                Bosnia and Herzegovina     3263459
20                         Botswana      1060.17         979.35          BWA               7.623306     117.0  0.693                                              Botswana     2397240
21                           Brazil      1837.56        1975.82          BRA              -7.524108      87.0  0.754                                                Brazil   213993441
22                         Bulgaria      1325.16        1229.79          BGR               7.196867      68.0  0.795                                              Bulgaria     6899125
23                     Burkina Faso      1425.64        1050.87          BFA              26.287843     184.0  0.449                                          Burkina Faso    21497097
24                          Burundi      1076.26         799.08          BDI              25.754000     187.0  0.426                                               Burundi    12255429
25                         Cambodia       954.30        1142.14          KHM             -19.683538     146.0  0.593                                              Cambodia    16946446
26                         Cameroon      1484.95        1417.44          CMR               4.546281     151.0  0.576                                              Cameroon    27224262
27                           Canada      1473.82        1986.51          CAN             -34.786473      15.0  0.936                                                Canada    38246108
28                            Chile      1514.86        1580.90          CHL              -4.359479      42.0  0.855                                                 Chile    19212362
29                         China PR      1305.06        1862.87          CHN             -42.742096      79.0  0.768                                                 China  1412360000
30                         Colombia      1604.07        1700.40          COL              -6.005349      88.0  0.752                                              Colombia    51265841
31                          Comoros      1127.44         733.00          COM              34.985454     156.0  0.558                                               Comoros      888456
32                            Congo      1215.09        1161.46          COG               4.413665     153.0  0.571                                           Congo, Rep.     5657017
33                         Congo DR      1332.84        1159.00          COD              13.042826     179.0  0.479                                      Congo, Dem. Rep.    92377986
34                       Costa Rica      1500.06        1612.44          CRI              -7.491700      58.0  0.809                                            Costa Rica     5139053
35                    Cote d'Ivoire      1435.91        1379.39          CIV               3.936180     159.0  0.550                                         Cote d'Ivoire    27053629
36                          Croatia      1632.15        1404.39          HRV              13.954600      40.0  0.858                                               Croatia     3899000
37                             Cuba       978.65        1217.56          CUB             -24.412200      83.0  0.764                                                  Cuba    11317498
38                           Cyprus      1180.52        1123.46          CYP               4.833463      29.0  0.896                                                Cyprus     1215588
39                          Czechia      1502.90        1675.21          CZE             -11.465167      32.0  0.889                                               Czechia    10703446
40                          Denmark      1665.47        1855.49          DNK             -11.409392       6.0  0.948                                               Denmark     5856733
41                         Dominica       911.51         910.74          DMA               0.084475     102.0  0.720                                              Dominica       72172
42               Dominican Republic      1031.86        1173.44          DOM             -13.720854      80.0  0.767                                    Dominican Republic    10953714
43                          Ecuador      1463.74        1377.83          ECU               5.869212      95.0  0.740                                               Ecuador    17888474
44                            Egypt      1482.63        1228.15          EGY              17.164094      97.0  0.731                                      Egypt, Arab Rep.   104258327
45                      El Salvador      1333.48        1148.88          SLV              13.843477     125.0  0.675                                           El Salvador     6518500
46                Equatorial Guinea      1215.33        1344.47          GNQ             -10.625921     145.0  0.596                                     Equatorial Guinea     1449891
47                          Estonia      1177.40        1180.34          EST              -0.249703      31.0  0.890                                               Estonia     1329254
48                         Eswatini      1070.89         807.89          SWZ              24.559012     144.0  0.597                                              Eswatini     1172369
49                         Ethiopia      1088.27        1117.66          ETH              -2.700617     175.0  0.498                                              Ethiopia   117876226
50                             Fiji       993.37        1345.58          FJI             -35.456074      99.0  0.730                                                  Fiji      902899
51                          Finland      1398.41        1669.24          FIN             -19.366995      11.0  0.940                                               Finland     5541696
52                           France      1764.85        2037.69          FRA             -15.459671      28.0  0.903                                                France    67499343
53                            Gabon      1301.84        1079.87          GAB              17.050482     112.0  0.706                                                 Gabon     2278829
54                           Gambia      1137.47        1124.04          GMB               1.180690     174.0  0.500                                           Gambia, The     2486937
55                          Georgia      1296.46        1118.09          GEO              13.758234      63.0  0.802                                               Georgia     3708610
56                          Germany      1658.96        2059.75          DEU             -24.159112       9.0  0.942                                               Germany    83129285
57                            Ghana      1393.47        1416.77          GHA              -1.672085     133.0  0.632                                                 Ghana    31732128
58                           Greece      1441.45        1409.31          GRC               2.229699      33.0  0.887                                                Greece    10664568
59                          Grenada       969.00         849.17          GRD              12.366357      68.0  0.795                                               Grenada      113015
60                        Guatemala      1161.96        1259.69          GTM              -8.410789     135.0  0.627                                             Guatemala    17109746
61                           Guinea      1294.89        1078.56          GIN              16.706438     182.0  0.465                                                Guinea    13497237
62                    Guinea-Bissau      1165.53         835.18          GNB              28.343329     177.0  0.483                                         Guinea-Bissau     2015490
63                           Guyana       968.74        1247.77          GUY             -28.803394     108.0  0.714                                                Guyana      790329
64                            Haiti      1269.07        1445.71          HTI             -13.918854     163.0  0.535                                                 Haiti    11541683
65                         Honduras      1299.69        1145.70          HND              11.848210     137.0  0.621                                              Honduras    10062994
66                        Hong Kong      1058.37        1314.35          HKG             -24.186249       4.0  0.952                                  Hong Kong SAR, China     7413100
67                          Hungary      1486.76        1538.35          HUN              -3.469962      46.0  0.846                                               Hungary     9709886
68                          Iceland      1379.61        1870.66          ISL             -35.593392       3.0  0.959                                               Iceland      372295
69                            India      1198.65        1425.51          IND             -18.926292     132.0  0.633                                                 India  1393409033
70                        Indonesia      1019.19        1209.02          IDN             -18.625575     114.0  0.705                                             Indonesia   276361788
71                          IR Iran      1558.64        1364.73          IRN              12.440974      76.0  0.774                                    Iran, Islamic Rep.    85028760
72                           Israel      1316.35        1365.34          ISR              -3.721655      22.0  0.919                                                Israel     9364000
73                            Italy      1713.86        1868.29          ITA              -9.010654      30.0  0.895                                                 Italy    59066225
74                          Jamaica      1382.06        1543.93          JAM             -11.712227     110.0  0.709                                               Jamaica     2973462
75                            Japan      1554.69        1917.07          JPN             -23.308827      19.0  0.925                                                 Japan   125681593
76                           Jordan      1279.74        1377.44          JOR              -7.634363     102.0  0.720                                                Jordan    10269022
77                       Kazakhstan      1166.28        1234.30          KAZ              -5.832219      56.0  0.811                                            Kazakhstan    19002586
78                            Kenya      1202.26         991.78          KEN              17.507028     152.0  0.575                                                 Kenya    54985702
79                   Korea Republic      1526.02        1850.09          KOR             -21.236288      19.0  0.925                                           Korea, Rep.    51744876
80                  Kyrgyz Republic      1232.91        1120.59          KGZ               9.110154     118.0  0.692                                       Kyrgyz Republic     6694200
81                             Laos       914.66        1257.98          LAO             -37.535259     140.0  0.607                                               Lao PDR     7379358
82                           Latvia      1125.36        1168.47          LVA              -3.830774      39.0  0.863                                                Latvia     1883162
83                          Lebanon      1211.71        1032.23          LBN              14.812125     112.0  0.706                                               Lebanon     6769151
84                          Lesotho      1061.40         842.00          LSO              20.670812     168.0  0.514                                               Lesotho     2159067
85                          Liberia      1051.25         891.31          LBR              15.214269     178.0  0.481                                               Liberia     5180208
86                        Lithuania      1074.08        1219.51          LTU             -13.539960      35.0  0.875                                             Lithuania     2795321
87                       Luxembourg      1235.36        1150.79          LUX               6.845778      17.0  0.930                                            Luxembourg      639070
88                       Madagascar      1193.78         691.00          MDG              42.116638     173.0  0.501                                            Madagascar    28427333
89                           Malawi      1144.77         942.66          MWI              17.655075     169.0  0.512                                                Malawi    19647681
90                         Malaysia      1057.59        1231.94          MYS             -16.485595      62.0  0.803                                              Malaysia    32776195
91                         Maldives      1018.25         952.73          MDV               6.434569      90.0  0.747                                              Maldives      543620
92                             Mali      1442.88        1273.24          MLI              11.757041     186.0  0.428                                                  Mali    20855724
93                            Malta       974.68        1231.00          MLT             -26.297862      23.0  0.918                                                 Malta      516869
94                        Mauritius       932.02         363.36          MUS              61.013712      63.0  0.802                                             Mauritius     1266060
95                           Mexico      1649.57        1628.95          MEX               1.250023      86.0  0.758                                                Mexico   130262220
96                          Moldova       944.96        1170.70          MDA             -23.888842      80.0  0.767                                               Moldova     2573928
97                         Mongolia       913.55        1111.95          MNG             -21.717476      96.0  0.739                                              Mongolia     3329282
98                       Montenegro      1354.59        1251.28          MNE               7.626662      49.0  0.832                                            Montenegro      620173
99                          Morocco      1558.35        1315.41          MAR              15.589566     123.0  0.683                                               Morocco    37344787
100                      Mozambique      1165.41         815.14          MOZ              30.055517     185.0  0.446                                            Mozambique    32163045
101                         Myanmar      1011.91        1517.95          MMR             -50.008400     149.0  0.585                                               Myanmar    54806014
102                         Namibia      1164.13        1020.53          NAM              12.335392     139.0  0.615                                               Namibia     2587344
103                           Nepal       950.45        1196.73          NPL             -25.911936     143.0  0.602                                                 Nepal    29674920
104                     Netherlands      1679.41        2002.99          NLD             -19.267481      10.0  0.941                                           Netherlands    17533405
105                     New Zealand      1198.96        1741.94          NZL             -45.287583      13.0  0.937                                           New Zealand     5122600
106                       Nicaragua      1079.18        1157.63          NIC              -7.269408     126.0  0.667                                             Nicaragua     6702379
107                           Niger      1155.23         877.93          NER              24.003878     189.0  0.400                                                 Niger    25130810

In [12]:
#rename columns
df.columns = ['Population' if x=='YR2021' else x for x in df.columns]
df.columns = ['HDI' if x=='Value' else x for x in df.columns]

In [7]:
#remove countries without data
df = df.dropna()

In [8]:
#check shape
df.shape

(163, 9)

In [10]:
#download csv
df.to_csv('HDIPoints.csv')

In [13]:
#format data for regression
X = df['Womens Points'].values[:, np.newaxis]

y = df['HDI'].values

In [14]:
#perform regression
import statsmodels.api as sm

x2 = sm.add_constant(X)

model = sm.OLS(y, x2).fit()
predictions = model.predict(x2)




model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.342
Model:                            OLS   Adj. R-squared:                  0.338
Method:                 Least Squares   F-statistic:                     83.67
Date:                Wed, 14 Dec 2022   Prob (F-statistic):           2.48e-16
Time:                        09:56:47   Log-Likelihood:                 115.81
No. Observations:                 163   AIC:                            -227.6
Df Residuals:                     161   BIC:                            -221.4
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.4001      0.037     10.734      0.000       0.326       0.474
x1             0.0003   2.77e-05      9.147      0.000       0.000       0.000
==============================================================================
Omnibus:                        1.114   Durbin-Watson:                   1.848
Prob(Omnibus):                  0.573   Jarque-Bera (JB):                1.132
Skew:                          -0.097   Prob(JB):                        0.568
Kurtosis:                       2.641   Cond. No.                     5.35e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.35e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""