In [1]:
#import packages
import pandas as pd
import numpy as np

In [2]:
#load datasets
df1 = pd.read_csv('HDIData1 - Sheet1.csv')

df2 = pd.read_csv('IsocodesMergedClean.csv')

In [3]:
#rename column
df1.columns = ['Country Name' if x=='Country' else x for x in df1.columns]

In [4]:
#merge datasets using outer method to check for matching errors
dfcheck = pd.merge(df1, df2, on ='Country Name', how = 'outer')

In [5]:
#check for matching errors
print(dfcheck.to_string())

     HDI rank                        Country Name  Value  Mens Points  Womens Points Alpha-3 code  Percentage Difference
0         1.0                         Switzerland  0.962      1621.43        1775.36          CHE              -9.493472
1         2.0                              Norway  0.961      1488.57        1889.96          NOR             -26.964805
2         3.0                             Iceland  0.959      1379.61        1870.66          ISL             -35.593392
3         4.0              Hong Kong, China (SAR)  0.952          NaN            NaN          NaN                    NaN
4         5.0                           Australia  0.951      1483.73        1906.20          AUS             -28.473509
5         6.0                             Denmark  0.948      1665.47        1855.49          DNK             -11.409392
6         7.0                              Sweden  0.947      1563.44        2050.18          SWE             -31.132631
7         8.0                             Ireland  0.945          NaN            NaN          NaN                    NaN
8         9.0                             Germany  0.942      1658.96        2059.75          DEU             -24.159112
9        10.0                         Netherlands  0.941      1679.41        2002.99          NLD             -19.267481
10       11.0                             Finland  0.940      1398.41        1669.24          FIN             -19.366995
11       12.0                           Singapore  0.939      1004.75        1088.77          SGP              -8.362279
12       13.0                             Belgium  0.937      1821.92        1823.83          BEL              -0.104834
13       13.0                         New Zealand  0.937      1198.96        1741.94          NZL             -45.287583
14       15.0                              Canada  0.936      1473.82        1986.51          CAN             -34.786473
15       16.0                       Liechtenstein  0.935          NaN            NaN          NaN                    NaN
16       17.0                          Luxembourg  0.930      1235.36        1150.79          LUX               6.845778
17       18.0                      United Kingdom  0.929          NaN            NaN          NaN                    NaN
18       19.0                               Japan  0.925      1554.69        1917.07          JPN             -23.308827
19       19.0                 Korea (Republic of)  0.925          NaN            NaN          NaN                    NaN
20       21.0                       United States  0.921          NaN            NaN          NaN                    NaN
21       22.0                              Israel  0.919      1316.35        1365.34          ISR              -3.721655
22       23.0                               Malta  0.918       974.68        1231.00          MLT             -26.297862
23       23.0                            Slovenia  0.918      1372.48        1536.95          SVN             -11.983417
24       25.0                             Austria  0.916      1502.47        1813.37          AUT             -20.692593
25       26.0                United Arab Emirates  0.911      1346.09        1181.72          ARE              12.210922
26       27.0                               Spain  0.905      1716.93        1983.13          ESP             -15.504418
27       28.0                              France  0.903      1764.85        2037.69          FRA             -15.459671
28       29.0                              Cyprus  0.896      1180.52        1123.46          CYP               4.833463
29       30.0                               Italy  0.895      1713.86        1868.29          ITA              -9.010654
30       31.0                             Estonia  0.890      1177.40        1180.34          EST              -0.249703
31       32.0                             Czechia  0.889      1502.90        1675.21          CZE             -11.465167
32       33.0                              Greece  0.887      1441.45        1409.31          GRC               2.229699
33       34.0                              Poland  0.876      1546.18        1647.92          POL              -6.580088
34       35.0                             Bahrain  0.875      1289.25        1254.12          BHR               2.724840
35       35.0                           Lithuania  0.875      1074.08        1219.51          LTU             -13.539960
36       35.0                        Saudi Arabia  0.875          NaN            NaN          NaN                    NaN
37       38.0                            Portugal  0.866      1678.65        1688.06          PRT              -0.560570
38       39.0                              Latvia  0.863      1125.36        1168.47          LVA              -3.830774
39       40.0                             Andorra  0.858      1028.70         751.46          AND              26.950520
40       40.0                             Croatia  0.858      1632.15        1404.39          HRV              13.954600
41       42.0                               Chile  0.855      1514.86        1580.90          CHL              -4.359479
42       42.0                               Qatar  0.855          NaN            NaN          NaN                    NaN
43       44.0                          San Marino  0.853          NaN            NaN          NaN                    NaN
44       45.0                            Slovakia  0.848      1439.99        1541.41          SVK              -7.043104
45       46.0                             Hungary  0.846      1486.76        1538.35          HUN              -3.469962
46       47.0                           Argentina  0.842      1770.65        1660.37          ARG               6.228221
47       48.0                             TÃ¼rkiye  0.838          NaN            NaN          NaN                    NaN
48       49.0                          Montenegro  0.832      1354.59        1251.28          MNE               7.626662
49       50.0                              Kuwait  0.831          NaN            NaN          NaN                    NaN
50       51.0                   Brunei Darussalam  0.829          NaN            NaN          NaN                    NaN
51       52.0                  Russian Federation  0.822          NaN            NaN          NaN                    NaN
52       53.0                             Romania  0.821      1427.84        1574.30          ROU             -10.257452
53       54.0                                Oman  0.816          NaN            NaN          NaN                    NaN
54       55.0                             Bahamas  0.812          NaN            NaN          NaN                    NaN
55       56.0                          Kazakhstan  0.811      1166.28        1234.30          KAZ              -5.832219
56       57.0                 Trinidad and Tobago  0.810      1205.85        1318.11          TTO              -9.309616
57       58.0                          Costa Rica  0.809      1500.06        1612.44          CRI              -7.491700
58       58.0                             Uruguay  0.809      1640.95        1374.14          URY              16.259484
59       60.0                             Belarus  0.808      1226.55        1457.75          BLR             -18.849619
60       61.0                              Panama  0.805      1389.27        1425.65          PAN              -2.618641
61       62.0                            Malaysia  0.803      1057.59        1231.94          MYS             -16.485595
62       63.0                             Georgia  0.802      1296.46        1118.09          GEO              13.758234
63       63.0                           Mauritius  0.802       932.02         363.36          MUS              61.013712
64       63.0                              Serbia  0.802      1549.53        1630.68          SRB              -5.237072
65       66.0                            Thailand  0.800      1170.69        1555.00          THA             -32.827649
66       67.0                             Albania  0.796      1361.81        1346.01          ALB               1.160221
67       68.0                            Bulgaria  0.795      1325.16        1229.79          BGR               7.196867
68       68.0                             Grenada  0.795       969.00         849.17          GRD              12.366357
69       70.0                            Barbados  0.790       982.27         966.80          BRB               1.574923
70       71.0                 Antigua and Barbuda  0.788      1117.01         804.42          ATG              27.984530
71       72.0                          Seychelles  0.785       860.48         884.64          SYC              -2.807735
72       73.0                           Sri Lanka  0.782       825.25         968.00          LKA             -17.297789
73       74.0              Bosnia and Herzegovina  0.780      1403.98        1385.20          BIH               1.337626
74       75.0               Saint Kitts and Nevis  0.777          NaN            NaN          NaN                    NaN
75       76.0          Iran (Islamic Republic of)  0.774          NaN            NaN          NaN                    NaN
76       77.0                             Ukraine  0.773      1542.79        1643.46          UKR              -6.525191
77       78.0                     North Macedonia  0.770      1375.20        1082.42          MKD              21.289994
78       79.0                               China  0.768          NaN            NaN          NaN                    NaN
79       80.0                  Dominican Republic  0.767      1031.86        1173.44          DOM             -13.720854
80       80.0               Moldova (Republic of)  0.767          NaN            NaN          NaN                    NaN
81       80.0                               Palau  0.767          NaN            NaN          NaN                    NaN
82       83.0                                Cuba  0.764       978.65        1217.56          CUB             -24.412200
83       84.0                                Peru  0.762      1562.24        1334.47          PER              14.579706
84       85.0                             Armenia  0.759      1242.42        1072.97          ARM              13.638705
85       86.0                              Mexico  0.758      1649.57        1628.95          MEX               1.250023
86       87.0                              Brazil  0.754      1837.56        1975.82          BRA              -7.524108
87       88.0                            Colombia  0.752      1604.07        1700.40          COL              -6.005349
88       89.0    Saint Vincent and the Grenadines  0.751          NaN            NaN          NaN                    NaN
89       90.0                            Maldives  0.747      1018.25         952.73          MDV               6.434569
90       91.0                             Algeria  0.745      1480.59        1288.27          DZA              12.989416
91       91.0                          Azerbaijan  0.745      1127.17        1274.50          AZE             -13.070788
92       91.0                               Tonga  0.745       861.81        1221.48          TON             -41.734257
93       91.0                        Turkmenistan  0.745      1100.47        1075.41          TKM               2.277209
94       95.0                             Ecuador  0.740      1463.74        1377.83          ECU               5.869212
95       96.0                            Mongolia  0.739       913.55        1111.95          MNG             -21.717476
96       97.0                               Egypt  0.731      1482.63        1228.15          EGY              17.164094
97       97.0                             Tunisia  0.731      1507.86        1298.60          TUN              13.877946
98       99.0                                Fiji  0.730       993.37        1345.58          FJI             -35.456074
99       99.0                            Suriname  0.730      1072.24        1089.15          SUR              -1.577072
100     101.0                          Uzbekistan  0.727      1306.63        1523.83          UZB             -16.622915
101     102.0                            Dominica  0.720       911.51         910.74          DMA               0.084475
102     102.0                              Jordan  0.720      1279.74        1377.44          JOR              -7.634363
103     104.0                               Libya  0.718          NaN            NaN          NaN                    NaN
104     105.0                            Paraguay  0.717      1440.13        1510.53          PRY              -4.888448
105     106.0                 Palestine, State of  0.715          NaN            NaN          NaN                    NaN
106     106.0                         Saint Lucia  0.715          NaN            NaN          NaN                    NaN
107     108.0                              Guyana  0.714       968.74        1247.77          GUY             -28.803394
108     109.0                        South Africa  0.713      1350.55        1464.36          ZAF              -8.426937
109     110.0                             Jamaica  0.709      1382.06        1543.93          JAM             -11.712227
110     111.0                               Samoa  0.707       894.26        1212.01          WSM             -35.532172
111     112.0                               Gabon  0.706      1301.84        1079.87          GAB              17.050482
112     112.0                             Lebanon  0.706      1211.71        1032.23          LBN              14.812125
113     114.0                           Indonesia  0.705      1019.19        1209.02          IDN             -18.625575
114     115.0                            Viet Nam  0.703          NaN            NaN          NaN                    NaN
115     116.0                         Philippines  0.699      1115.13        1479.91          PHL             -32.711881
116     117.0                            Botswana  0.693      1060.17         979.35          BWA               7.623306
117     118.0    Bolivia (Plurinational State of)  0.692          NaN            NaN          NaN                    NaN
118     118.0                          Kyrgyzstan  0.692          NaN            NaN          NaN                    NaN
119     120.0  Venezuela (Bolivarian Republic of)  0.691          NaN            NaN          NaN                    NaN
120     121.0                                Iraq  0.686          NaN            NaN          NaN                    NaN
121     122.0                          Tajikistan  0.685      1179.10        1033.87          TJK              12.317021
122     123.0                              Belize  0.683       950.88         839.85          BLZ              11.676552
123     123.0                             Morocco  0.683      1558.35        1315.41          MAR              15.589566
124     125.0                         El Salvador  0.675      1333.48        1148.88          SLV              13.843477
125     126.0                           Nicaragua  0.667      1079.18        1157.63          NIC              -7.269408
126     127.0                              Bhutan  0.666       910.96         769.00          BTN              15.583560
127     128.0                          Cabo Verde  0.662          NaN            NaN          NaN                    NaN
128     129.0                          Bangladesh  0.661       883.18        1017.16          BGD             -15.170180
129     130.0                              Tuvalu  0.641          NaN            NaN          NaN                    NaN
130     131.0                    Marshall Islands  0.639          NaN            NaN          NaN                    NaN
131     132.0                               India  0.633      1198.65        1425.51          IND             -18.926292
132     133.0                               Ghana  0.632      1393.47        1416.77          GHA              -1.672085
133     134.0    Micronesia (Federated States of)  0.628          NaN            NaN          NaN                    NaN
134     135.0                           Guatemala  0.627      1161.96        1259.69          GTM              -8.410789
135     136.0                            Kiribati  0.624          NaN            NaN          NaN                    NaN
136     137.0                            Honduras  0.621      1299.69        1145.70          HND              11.848210
137     138.0               Sao Tome and Principe  0.618          NaN            NaN          NaN                    NaN
138     139.0                             Namibia  0.615      1164.13        1020.53          NAM              12.335392
139     140.0    Lao People's Democratic Republic  0.607          NaN            NaN          NaN                    NaN
140     140.0                         Timor-Leste  0.607       860.06         973.91          TLS             -13.237449
141     140.0                             Vanuatu  0.607       990.55        1132.82          VUT             -14.362728
142     143.0                               Nepal  0.602       950.45        1196.73          NPL             -25.911936
143     144.0               Eswatini (Kingdom of)  0.597          NaN            NaN          NaN                    NaN
144     145.0                   Equatorial Guinea  0.596      1215.33        1344.47          GNQ             -10.625921
145     146.0                            Cambodia  0.593       954.30        1142.14          KHM             -19.683538
146     146.0                            Zimbabwe  0.593      1138.56        1115.59          ZWE               2.017461
147     148.0                              Angola  0.586      1149.08        1041.91          AGO               9.326592
148     149.0                             Myanmar  0.585      1011.91        1517.95          MMR             -50.008400
149     150.0                Syrian Arab Republic  0.577          NaN            NaN          NaN                    NaN
150     151.0                            Cameroon  0.576      1484.95        1417.44          CMR               4.546281
151     152.0                               Kenya  0.575      1202.26         991.78          KEN              17.507028
152     153.0                               Congo  0.571      1215.09        1161.46          COG               4.413665
153     154.0                              Zambia  0.565      1270.80        1280.19          ZMB              -0.738905
154     155.0                     Solomon Islands  0.564      1092.56        1181.11          SLB              -8.104818
155     156.0                             Comoros  0.558      1127.44         733.00          COM              34.985454
156     156.0                    Papua New Guinea  0.558       997.60        1512.43          PNG             -51.606856
157     158.0                          Mauritania  0.556          NaN            NaN          NaN                    NaN
158     159.0                       CÃ´te d'Ivoire  0.550          NaN            NaN          NaN                    NaN
159     160.0       Tanzania (United Republic of)  0.549          NaN            NaN          NaN                    NaN
160     161.0                            Pakistan  0.544          NaN            NaN          NaN                    NaN
161     162.0                                Togo  0.539      1130.22        1138.33          TGO              -0.717559
162     163.0                               Haiti  0.535      1269.07        1445.71          HTI             -13.918854
163     163.0                             Nigeria  0.535      1504.70        1535.09          NGA              -2.019672

In [6]:
#correct matching errors in excel
dfcheck.to_csv('HDICheck.csv')

In [7]:
#load cleaned data
df3 = pd.read_csv('HDIDataCleaned.csv')

In [8]:
#rename columns
df3.columns = ['Country Name' if x=='Country' else x for x in df1.columns]

In [9]:
#merge using outer to check for any missed errors
df = pd.merge(df2, df3, on ='Country Name', how = 'outer')

In [10]:
#check for erros
print(df.to_string())

                         Country Name  Mens Points  Womens Points Alpha-3 code  Percentage Difference  HDI rank  Value
0                             Albania      1361.81        1346.01          ALB               1.160221      67.0  0.796
1                             Algeria      1480.59        1288.27          DZA              12.989416      91.0  0.745
2                      American Samoa       900.27        1030.00          ASM             -14.410121       NaN    NaN
3                             Andorra      1028.70         751.46          AND              26.950520      40.0  0.858
4                              Angola      1149.08        1041.91          AGO               9.326592     148.0  0.586
5                            Anguilla       790.74         687.55          AIA              13.049801       NaN    NaN
6                 Antigua and Barbuda      1117.01         804.42          ATG              27.984530      71.0  0.788
7                           Argentina      1770.65        1660.37          ARG               6.228221      47.0  0.842
8                             Armenia      1242.42        1072.97          ARM              13.638705      85.0  0.759
9                               Aruba       855.37         728.86          ABW              14.790091       NaN    NaN
10                          Australia      1483.73        1906.20          AUS             -28.473509       5.0  0.951
11                            Austria      1502.47        1813.37          AUT             -20.692593      25.0  0.916
12                         Azerbaijan      1127.17        1274.50          AZE             -13.070788      91.0  0.745
13                            Bahrain      1289.25        1254.12          BHR               2.724840      35.0  0.875
14                         Bangladesh       883.18        1017.16          BGD             -15.170180     129.0  0.661
15                           Barbados       982.27         966.80          BRB               1.574923      70.0  0.790
16                            Belarus      1226.55        1457.75          BLR             -18.849619      60.0  0.808
17                            Belgium      1821.92        1823.83          BEL              -0.104834      13.0  0.937
18                             Belize       950.88         839.85          BLZ              11.676552     123.0  0.683
19                              Benin      1258.71        1020.94          BEN              18.889975     166.0  0.525
20                            Bermuda       977.47        1007.55          BMU              -3.077332       NaN    NaN
21                             Bhutan       910.96         769.00          BTN              15.583560     127.0  0.666
22                            Bolivia      1298.81        1213.10          BOL               6.599118     118.0  0.692
23             Bosnia and Herzegovina      1403.98        1385.20          BIH               1.337626      74.0  0.780
24                           Botswana      1060.17         979.35          BWA               7.623306     117.0  0.693
25                             Brazil      1837.56        1975.82          BRA              -7.524108      87.0  0.754
26                           Bulgaria      1325.16        1229.79          BGR               7.196867      68.0  0.795
27                       Burkina Faso      1425.64        1050.87          BFA              26.287843     184.0  0.449
28                            Burundi      1076.26         799.08          BDI              25.754000     187.0  0.426
29                           Cambodia       954.30        1142.14          KHM             -19.683538     146.0  0.593
30                           Cameroon      1484.95        1417.44          CMR               4.546281     151.0  0.576
31                             Canada      1473.82        1986.51          CAN             -34.786473      15.0  0.936
32                     Cayman Islands       865.72         854.05          CYM               1.348011       NaN    NaN
33                              Chile      1514.86        1580.90          CHL              -4.359479      42.0  0.855
34                           China PR      1305.06        1862.87          CHN             -42.742096      79.0  0.768
35                             Taiwan      1017.78        1581.20          TWN             -55.357739       NaN    NaN
36                           Colombia      1604.07        1700.40          COL              -6.005349      88.0  0.752
37                            Comoros      1127.44         733.00          COM              34.985454     156.0  0.558
38                              Congo      1215.09        1161.46          COG               4.413665     153.0  0.571
39                           Congo DR      1332.84        1159.00          COD              13.042826     179.0  0.479
40                       Cook Islands       899.33        1174.93          COK             -30.645036       NaN    NaN
41                         Costa Rica      1500.06        1612.44          CRI              -7.491700      58.0  0.809
42                      Cote d'Ivoire      1435.91        1379.39          CIV               3.936180     159.0  0.550
43                            Croatia      1632.15        1404.39          HRV              13.954600      40.0  0.858
44                               Cuba       978.65        1217.56          CUB             -24.412200      83.0  0.764
45                             Cyprus      1180.52        1123.46          CYP               4.833463      29.0  0.896
46                            Czechia      1502.90        1675.21          CZE             -11.465167      32.0  0.889
47                            Denmark      1665.47        1855.49          DNK             -11.409392       6.0  0.948
48                           Dominica       911.51         910.74          DMA               0.084475     102.0  0.720
49                 Dominican Republic      1031.86        1173.44          DOM             -13.720854      80.0  0.767
50                            Ecuador      1463.74        1377.83          ECU               5.869212      95.0  0.740
51                              Egypt      1482.63        1228.15          EGY              17.164094      97.0  0.731
52                        El Salvador      1333.48        1148.88          SLV              13.843477     125.0  0.675
53                  Equatorial Guinea      1215.33        1344.47          GNQ             -10.625921     145.0  0.596
54                            Estonia      1177.40        1180.34          EST              -0.249703      31.0  0.890
55                           Eswatini      1070.89         807.89          SWZ              24.559012     144.0  0.597
56                           Ethiopia      1088.27        1117.66          ETH              -2.700617     175.0  0.498
57                      Faroe Islands      1136.29        1211.40          FRO              -6.610108       NaN    NaN
58                               Fiji       993.37        1345.58          FJI             -35.456074      99.0  0.730
59                            Finland      1398.41        1669.24          FIN             -19.366995      11.0  0.940
60                             France      1764.85        2037.69          FRA             -15.459671      28.0  0.903
61                              Gabon      1301.84        1079.87          GAB              17.050482     112.0  0.706
62                             Gambia      1137.47        1124.04          GMB               1.180690     174.0  0.500
63                            Georgia      1296.46        1118.09          GEO              13.758234      63.0  0.802
64                            Germany      1658.96        2059.75          DEU             -24.159112       9.0  0.942
65                              Ghana      1393.47        1416.77          GHA              -1.672085     133.0  0.632
66                             Greece      1441.45        1409.31          GRC               2.229699      33.0  0.887
67                            Grenada       969.00         849.17          GRD              12.366357      68.0  0.795
68                               Guam       838.33        1218.07          GUM             -45.297198       NaN    NaN
69                          Guatemala      1161.96        1259.69          GTM              -8.410789     135.0  0.627
70                             Guinea      1294.89        1078.56          GIN              16.706438     182.0  0.465
71                      Guinea-Bissau      1165.53         835.18          GNB              28.343329     177.0  0.483
72                             Guyana       968.74        1247.77          GUY             -28.803394     108.0  0.714
73                              Haiti      1269.07        1445.71          HTI             -13.918854     163.0  0.535
74                           Honduras      1299.69        1145.70          HND              11.848210     137.0  0.621
75                          Hong Kong      1058.37        1314.35          HKG             -24.186249       4.0  0.952
76                            Hungary      1486.76        1538.35          HUN              -3.469962      46.0  0.846
77                            Iceland      1379.61        1870.66          ISL             -35.593392       3.0  0.959
78                              India      1198.65        1425.51          IND             -18.926292     132.0  0.633
79                          Indonesia      1019.19        1209.02          IDN             -18.625575     114.0  0.705
80                            IR Iran      1558.64        1364.73          IRN              12.440974      76.0  0.774
81                             Israel      1316.35        1365.34          ISR              -3.721655      22.0  0.919
82                              Italy      1713.86        1868.29          ITA              -9.010654      30.0  0.895
83                            Jamaica      1382.06        1543.93          JAM             -11.712227     110.0  0.709
84                              Japan      1554.69        1917.07          JPN             -23.308827      19.0  0.925
85                             Jordan      1279.74        1377.44          JOR              -7.634363     102.0  0.720
86                         Kazakhstan      1166.28        1234.30          KAZ              -5.832219      56.0  0.811
87                              Kenya      1202.26         991.78          KEN              17.507028     152.0  0.575
88                          Korea DPR      1169.96        1940.00          PRK             -65.817635       NaN    NaN
89                     Korea Republic      1526.02        1850.09          KOR             -21.236288      19.0  0.925
90                    Kyrgyz Republic      1232.91        1120.59          KGZ               9.110154     118.0  0.692
91                               Laos       914.66        1257.98          LAO             -37.535259     140.0  0.607
92                             Latvia      1125.36        1168.47          LVA              -3.830774      39.0  0.863
93                            Lebanon      1211.71        1032.23          LBN              14.812125     112.0  0.706
94                            Lesotho      1061.40         842.00          LSO              20.670812     168.0  0.514
95                            Liberia      1051.25         891.31          LBR              15.214269     178.0  0.481
96                          Lithuania      1074.08        1219.51          LTU             -13.539960      35.0  0.875
97                         Luxembourg      1235.36        1150.79          LUX               6.845778      17.0  0.930
98                         Madagascar      1193.78         691.00          MDG              42.116638     173.0  0.501
99                             Malawi      1144.77         942.66          MWI              17.655075     169.0  0.512
100                          Malaysia      1057.59        1231.94          MYS             -16.485595      62.0  0.803
101                          Maldives      1018.25         952.73          MDV               6.434569      90.0  0.747
102                              Mali      1442.88        1273.24          MLI              11.757041     186.0  0.428
103                             Malta       974.68        1231.00          MLT             -26.297862      23.0  0.918
104                         Mauritius       932.02         363.36          MUS              61.013712      63.0  0.802
105                            Mexico      1649.57        1628.95          MEX               1.250023      86.0  0.758
106                           Moldova       944.96        1170.70          MDA             -23.888842      80.0  0.767
107                          Mongolia       913.55        1111.95          MNG             -21.717476      96.0  0.739
108                        Montenegro      1354.59        1251.28          MNE               7.626662      49.0  0.832
109                           Morocco      1558.35        1315.41          MAR              15.589566     123.0  0.683
110                        Mozambique      1165.41         815.14          MOZ              30.055517     185.0  0.446
111                           Myanmar      1011.91        1517.95          MMR             -50.008400     149.0  0.585
112                           Namibia      1164.13        1020.53          NAM              12.335392     139.0  0.615
113                             Nepal       950.45        1196.73          NPL             -25.911936     143.0  0.602
114                       Netherlands      1679.41        2002.99          NLD             -19.267481      10.0  0.941
115                     New Caledonia       999.70        1175.63          NCL             -17.598279       NaN    NaN
116                       New Zealand      1198.96        1741.94          NZL             -45.287583      13.0  0.937
117                         Nicaragua      1079.18        1157.63          NIC              -7.269408     126.0  0.667
118                             Niger      1155.23         877.93          NER              24.003878     189.0  0.400
119                           Nigeria      1504.70        1535.09          NGA              -2.019672     163.0  0.535
120                   North Macedonia      1375.20        1082.42          MKD              21.289994      78.0  0.770
121                            Norway      1488.57        1889.96          NOR             -26.964805       2.0  0.961
122                         Palestine      1233.72        1103.05          PSE              10.591544     106.0  0.715
123                            Panama      1389.27        1425.65          PAN              -2.618641      61.0  0.805
124                  Papua New Guinea       997.60        1512.43          PNG             -51.606856     156.0  0.558
125                          Paraguay      1440.13        1510.53          PRY              -4.888448     105.0  0.717
126                              Peru      1562.24        1334.47          PER              14.579706      84.0  0.762
127                       Philippines      1115.13        1479.91          PHL             -32.711881     116.0  0.699
128                            Poland      1546.18        1647.92          POL              -6.580088      34.0  0.876
129                          Portugal      1678.65        1688.06          PRT              -0.560570      38.0  0.866
130                       Puerto Rico       974.32        1186.72          PRI             -21.799819       NaN    NaN
131               Republic of Ireland      1442.48        1695.26          IRL             -17.523986       8.0  0.945
132                           Romania      1427.84        1574.30          ROU             -10.257452      53.0  0.821
133                            Russia      1493.42        1717.04          RUS             -14.973685      52.0  0.822
134                            Rwanda      1095.04         894.87          RWA              18.279698     165.0  0.534
135                             Samoa       894.26        1212.01          WSM             -35.532172     111.0  0.707
136                           Senegal      1584.59        1258.35          SEN              20.588291     170.0  0.511
137                            Serbia      1549.53        1630.68          SRB              -5.237072      63.0  0.802
138                        Seychelles       860.48         884.64          SYC              -2.807735      72.0  0.785
139                      Sierra Leone      1169.71        1073.89          SLE               8.191774     181.0  0.477
140                         Singapore      1004.75        1088.77          SGP              -8.362279      12.0  0.939
141                          Slovakia      1439.99        1541.41          SVK              -7.043104      45.0  0.848
142                          Slovenia      1372.48        1536.95          SVN             -11.983417      23.0  0.918
143                   Solomon Islands      1092.56        1181.11          SLB              -8.104818     155.0  0.564
144                      South Africa      1350.55        1464.36          ZAF              -8.426937     109.0  0.713
145                       South Sudan       983.99         649.69          SSD              33.973923     191.0  0.385
146                             Spain      1716.93        1983.13          ESP             -15.504418      27.0  0.905
147                         Sri Lanka       825.25         968.00          LKA             -17.297789      73.0  0.782
148               St. Kitts and Nevis      1076.91        1090.74          KNA              -1.284230      75.0  0.777
149                         St. Lucia       965.66         982.00          LCA              -1.692107     106.0  0.715
150    St. Vincent and the Grenadines       939.97         950.85          VCT              -1.157484      89.0  0.751
151                          Suriname      1072.24        1089.15          SUR              -1.577072      99.0  0.730
152                            Sweden      1563.44        2050.18          SWE             -31.132631       7.0  0.947
153                       Switzerland      1621.43        1775.36          CHE              -9.493472       1.0  0.962
154                        Tajikistan      1179.10        1033.87          TJK              12.317021     122.0  0.685
155                          Tanzania      1121.91         965.82          TZA              13.912881     160.0  0.549
156                          Thailand      1170.69        1555.00          THA             -32.827649      66.0  0.800
157                       Timor-Leste       860.06         973.91          TLS             -13.237449     140.0  0.607
158                              Togo      1130.22        1138.33          TGO              -0.717559     162.0  0.539
159                             Tonga       861.81        1221.48          TON             -41.734257      91.0  0.745
160               Trinidad and Tobago      1205.85        1318.11          TTO              -9.309616      57.0  0.810
161                           Tunisia      1507.86        1298.60          TUN              13.877946      97.0  0.731
162                           Turkiye      1475.13        1374.84          TUR               6.798723      48.0  0.838
163                      Turkmenistan      1100.47        1075.41          TKM               2.277209      91.0  0.745
164          Turks and Caicos Islands       832.00         664.95          TCA              20.078125       NaN    NaN
165                            Uganda      1264.56         924.09          UGA              26.923989     166.0  0.525
166                           Ukraine      1542.79        1643.46          UKR              -6.525191      77.0  0.773

In [11]:
#remove any country without data
df = df.dropna()

In [12]:
df.head()

,Country Name,Mens Points,Womens Points,Alpha-3 code,Percentage Difference,HDI rank,Value
0,Albania,1361.81,1346.01,ALB,1.160221,67.0,0.796
1,Algeria,1480.59,1288.27,DZA,12.989416,91.0,0.745
3,Andorra,1028.70,751.46,AND,26.950520,40.0,0.858
4,Angola,1149.08,1041.91,AGO,9.326592,148.0,0.586
6,Antigua and Barbuda,1117.01,804.42,ATG,27.984530,71.0,0.788

In [13]:
#check shape
df.shape

(163, 7)

In [14]:
#download data as csv
df.to_csv('HDIPercentDiff.csv')

In [15]:
#format data for regression
X = df['Percentage Difference'].values[:, np.newaxis]

y = df['Value'].values

In [16]:
#perform regression
import statsmodels.api as sm


x2 = sm.add_constant(X)

model = sm.OLS(y, x2).fit()
predictions = model.predict(x2)



model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.170
Model:                            OLS   Adj. R-squared:                  0.165
Method:                 Least Squares   F-statistic:                     32.91
Date:                Wed, 14 Dec 2022   Prob (F-statistic):           4.66e-08
Time:                        10:56:12   Log-Likelihood:                 96.857
No. Observations:                 163   AIC:                            -189.7
Df Residuals:                     161   BIC:                            -183.5
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.7217      0.011     67.911      0.000       0.701       0.743
x1            -0.0032      0.001     -5.737      0.000      -0.004      -0.002
==============================================================================
Omnibus:                       21.550   Durbin-Watson:                   1.659
Prob(Omnibus):                  0.000   Jarque-Bera (JB):                7.690
Skew:                          -0.254   Prob(JB):                       0.0214
Kurtosis:                       2.065   Cond. No.                         19.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""